In [1]:
#!pip install pyzotero
import requests
import sddk
import getpass

# Zotero API configuration

1. find your zotero user ID and insert it interactively in the cell below (you can find it e.g. from https://www.zotero.org/settings/keys)

In [2]:
userID = input("Paste your Zotero user ID: ")

Paste your Zotero user ID: 5925766


2. go to https://www.zotero.org/settings/keys
3. `Create new private key`
4. name your key in `Key description`, e.g. `pyzot`.
5. click at `Save Key`
6. copy the generated key into clipboard
7 insert it in the cell below

In [3]:
api_key =  getpass.getpass("Paste your key: ")

Paste your key: ········


In [6]:
# prepare the authorization
base_url = "https://api.zotero.org/users/" + str(userID) + "/"
headers ={"Authorization": "Bearer " + api_key}

In [8]:
# list all personal collections
url = "https://api.zotero.org/users/5925766/collections"
resp = requests.get(url, headers=headers)
resp.json()

[{'key': 'LFPMLWZ2',
  'version': 77,
  'library': {'type': 'user',
   'id': 5925766,
   'name': 'petrifiedvoices',
   'links': {'alternate': {'href': 'https://www.zotero.org/petrifiedvoices',
     'type': 'text/html'}}},
  'links': {'self': {'href': 'https://api.zotero.org/users/5925766/collections/LFPMLWZ2',
    'type': 'application/json'},
   'alternate': {'href': 'https://www.zotero.org/petrifiedvoices/collections/LFPMLWZ2',
    'type': 'text/html'}},
  'meta': {'numCollections': 0, 'numItems': 78},
  'data': {'key': 'LFPMLWZ2',
   'version': 77,
   'name': 'JDH_article',
   'parentCollection': False,
   'relations': {}}}]

Among these collections, find the one you want to use and copy its `key` (i.e. the value of the `key` attribute. 

In [16]:
collection_key = input("your collection key: ")

your collection key: LFPMLWZ2


In [17]:
# list all items within preselected collection:
url = "https://api.zotero.org/users/5925766/collections/" + collection_key + "/items?limit=1000"
collection_items_json = requests.get(url, headers=headers).json()

In [18]:
# inspect the items
collection_items_json

[{'key': '5DKTH37I',
  'version': 134,
  'library': {'type': 'user',
   'id': 5925766,
   'name': 'petrifiedvoices',
   'links': {'alternate': {'href': 'https://www.zotero.org/petrifiedvoices',
     'type': 'text/html'}}},
  'links': {'self': {'href': 'https://api.zotero.org/users/5925766/items/5DKTH37I',
    'type': 'application/json'},
   'alternate': {'href': 'https://www.zotero.org/petrifiedvoices/items/5DKTH37I',
    'type': 'text/html'},
   'up': {'href': 'https://api.zotero.org/users/5925766/items/8C5W7WYE',
    'type': 'application/json'},
   'enclosure': {'type': 'application/pdf',
    'href': 'https://api.zotero.org/users/5925766/items/5DKTH37I/file/view',
    'title': 'Lowndes et al. - 2017 - Our path to better science in less time using open.pdf',
    'length': 412129}},
  'meta': {'numChildren': False},
  'data': {'key': '5DKTH37I',
   'version': 134,
   'parentItem': '8C5W7WYE',
   'itemType': 'attachment',
   'linkMode': 'imported_url',
   'title': 'Full Text',
   'acces

In [19]:
# ids of items
citation_keys_pairs = {}
for item in collection_items_json:
    if item["data"]["itemType"] != "attachment":
        try:
            item_key = item["meta"]["creatorSummary"] + " " + item["meta"]["parsedDate"]
        except: 
            try:
                item_key = item["data"]["title"]
            except:
                item_key = ""
        citation_keys_pairs[item_key] = item["data"]["key"]

In [20]:
citation_keys_pairs

{'Lowndes et al. 2017': '8C5W7WYE',
 'Scheidel 2018': '3J5XSHJ2',
 'Huggett 2017-05-23': 'CY54CMQ9',
 'Huggett 2016-06-29': 'QZV4FHQ6',
 'Raymond 2001': '3NH6EHMA',
 'Iversen 2007': 'CAJ8RP6I',
 'Sherratt 2019-10-29': 'GZXS5Q8K',
 'Madzharov 2009': 'XDAURK5G',
 'Hollenstein 1975': '7DY6HUZB',
 'Duncan-Jones 2018': 'J6GWZWL4',
 'Duncan-Jones 1990-04-12': 'YFQQLVBK',
 'Duncan-Jones 1996': 'HCU3WEJB',
 'Tahmasebi and Hengchen 2019': 'UH4L3837',
 'Wilson 2009': 'TARVRY26',
 'Liuzzo 2019-10-17': 'WRRYLBT4',
 'Wilkinson et al. 2016': 'VI7N28PJ',
 'Ballsun-Stanton 2020': 'KGBLD6FY',
 'Kolb 2019-06-17': 'MCUQLXCG',
 'Ober 2015': 'RB28J3CE',
 'Morris 2010': 'TGQ9TAPF',
 'Morris 2013': '93X7WDDV',
 'Hanson et al. 2017': 'WZ6MD9YX',
 'Mullins et al. 2018': '2ASLDCJP',
 'Borgman 2015': 'FBAWXZ3I',
 'Cayless et al. 2010-12-31': 'EYTI8IQA',
 'Laurence 1999': 'QSJYQVZZ',
 'Bodard 2008': 'KE9T4566',
 'Bodard et al. 2021-03-26': '2KEXYJLP',
 'Avanzini et al. 2018-12-31': '7EHKTWQD',
 'Liuzzo 2018-12-31

# Test with one item

In [23]:
item_id = "RAG327R6"
url = "https://api.zotero.org/users/5925766/items/" + item_id + "?format=csljson"
item_json = requests.get(url, headers=headers).json()
item_json

{'items': [{'id': '7109337/RAG327R6',
   'type': 'chapter',
   'title': 'Inscribing Identity: The Latin Epigraphic Habit in Late Antiquity',
   'container-title': 'A Companion to Late Antiquity',
   'publisher': 'John Wiley & Sons, Ltd',
   'page': '170-186',
   'abstract': 'This chapter contains sections titled: Epigraphic Corpora and Epigraphic Curves An Epigraphy of Christians Epigraphic Horizons Civic History and Public Memory Crossing Divides Bibliographical Note',
   'URL': 'https://onlinelibrary.wiley.com/doi/abs/10.1002/9781444306101.ch12',
   'ISBN': '978-1-4443-0610-1',
   'note': 'DOI: 10.1002/9781444306101.ch12',
   'shortTitle': 'Inscribing Identity',
   'language': 'en',
   'author': [{'family': 'Trout', 'given': 'Dennis E.'}],
   'issued': {'date-parts': [[2009]]},
   'accessed': {'date-parts': [[2021, 5, 7]]}}]}

In [24]:
# list all items within preselected collection:
url = "https://api.zotero.org/users/5925766/collections/" + collection_key + "/items?limit=1000&format=csljson"
collection_items_csljson = requests.get(url, headers=headers).json()
collection_items_csljson["items"][:5]

[{'id': '7109337/5DKTH37I',
  'type': 'article',
  'title': 'Full Text',
  'URL': 'https://www.nature.com/articles/s41559-017-0160.pdf',
  'accessed': {'date-parts': [[2021, 6, 11]]}},
 {'id': '7109337/8C5W7WYE',
  'type': 'article-journal',
  'title': 'Our path to better science in less time using open data science tools',
  'container-title': 'Nature Ecology & Evolution',
  'page': '0160',
  'volume': '1',
  'issue': '6',
  'URL': 'http://www.nature.com/articles/s41559-017-0160',
  'DOI': '10.1038/s41559-017-0160',
  'journalAbbreviation': 'Nat Ecol Evol',
  'language': 'en',
  'author': [{'family': 'Lowndes', 'given': 'Julia S. Stewart'},
   {'family': 'Best', 'given': 'Benjamin D.'},
   {'family': 'Scarborough', 'given': 'Courtney'},
   {'family': 'Afflerbach', 'given': 'Jamie C.'},
   {'family': 'Frazier', 'given': 'Melanie R.'},
   {'family': 'O’Hara', 'given': 'Casey C.'},
   {'family': 'Jiang', 'given': 'Ning'},
   {'family': 'Halpern', 'given': 'Benjamin S.'}],
  'issued': {'d

In [25]:
citations = {}
for item in collection_items_csljson["items"]:
    try:
        citations[item["id"]] = item
        citations[item["id"]].pop("id", None)
    except:
        pass

In [26]:
citations

{'7109337/5DKTH37I': {'type': 'article',
  'title': 'Full Text',
  'URL': 'https://www.nature.com/articles/s41559-017-0160.pdf',
  'accessed': {'date-parts': [[2021, 6, 11]]}},
 '7109337/8C5W7WYE': {'type': 'article-journal',
  'title': 'Our path to better science in less time using open data science tools',
  'container-title': 'Nature Ecology & Evolution',
  'page': '0160',
  'volume': '1',
  'issue': '6',
  'URL': 'http://www.nature.com/articles/s41559-017-0160',
  'DOI': '10.1038/s41559-017-0160',
  'journalAbbreviation': 'Nat Ecol Evol',
  'language': 'en',
  'author': [{'family': 'Lowndes', 'given': 'Julia S. Stewart'},
   {'family': 'Best', 'given': 'Benjamin D.'},
   {'family': 'Scarborough', 'given': 'Courtney'},
   {'family': 'Afflerbach', 'given': 'Jamie C.'},
   {'family': 'Frazier', 'given': 'Melanie R.'},
   {'family': 'O’Hara', 'given': 'Casey C.'},
   {'family': 'Jiang', 'given': 'Ning'},
   {'family': 'Halpern', 'given': 'Benjamin S.'}],
  'issued': {'date-parts': [['2

In [27]:
# list all items within preselected collection:
url = "https://api.zotero.org/users/5925766/collections/" + collection_key + "/items?limit=1000"
collection_items_rawjson = requests.get(url, headers=headers).json()
collection_items_rawjson[:5]

[{'key': '5DKTH37I',
  'version': 134,
  'library': {'type': 'user',
   'id': 5925766,
   'name': 'petrifiedvoices',
   'links': {'alternate': {'href': 'https://www.zotero.org/petrifiedvoices',
     'type': 'text/html'}}},
  'links': {'self': {'href': 'https://api.zotero.org/users/5925766/items/5DKTH37I',
    'type': 'application/json'},
   'alternate': {'href': 'https://www.zotero.org/petrifiedvoices/items/5DKTH37I',
    'type': 'text/html'},
   'up': {'href': 'https://api.zotero.org/users/5925766/items/8C5W7WYE',
    'type': 'application/json'},
   'enclosure': {'type': 'application/pdf',
    'href': 'https://api.zotero.org/users/5925766/items/5DKTH37I/file/view',
    'title': 'Lowndes et al. - 2017 - Our path to better science in less time using open.pdf',
    'length': 412129}},
  'meta': {'numChildren': False},
  'data': {'key': '5DKTH37I',
   'version': 134,
   'parentItem': '8C5W7WYE',
   'itemType': 'attachment',
   'linkMode': 'imported_url',
   'title': 'Full Text',
   'acces

In [28]:
collection_items_dict = dict([(el["key"], el) for el in collection_items_rawjson])

In [29]:
collection_items_dict

{'5DKTH37I': {'key': '5DKTH37I',
  'version': 134,
  'library': {'type': 'user',
   'id': 5925766,
   'name': 'petrifiedvoices',
   'links': {'alternate': {'href': 'https://www.zotero.org/petrifiedvoices',
     'type': 'text/html'}}},
  'links': {'self': {'href': 'https://api.zotero.org/users/5925766/items/5DKTH37I',
    'type': 'application/json'},
   'alternate': {'href': 'https://www.zotero.org/petrifiedvoices/items/5DKTH37I',
    'type': 'text/html'},
   'up': {'href': 'https://api.zotero.org/users/5925766/items/8C5W7WYE',
    'type': 'application/json'},
   'enclosure': {'type': 'application/pdf',
    'href': 'https://api.zotero.org/users/5925766/items/5DKTH37I/file/view',
    'title': 'Lowndes et al. - 2017 - Our path to better science in less time using open.pdf',
    'length': 412129}},
  'meta': {'numChildren': False},
  'data': {'key': '5DKTH37I',
   'version': 134,
   'parentItem': '8C5W7WYE',
   'itemType': 'attachment',
   'linkMode': 'imported_url',
   'title': 'Full Text

In [30]:
import re

In [44]:
re.match("(\d{4})-(\d+)\-(\d+)", "2018-07-08").groups()

('2018', '07', '08')

In [48]:
re.sub(r"(\d{4})-(\d+)\-(\d+)", r"\1", "2018-07-08")

'2018'

In [31]:
# ids of items
citation_keys_pairs = {}
for key in citations.keys():
    if collection_items_dict[key.rpartition("/")[2]]["data"]["itemType"] != "attachment":
        try:
            item_dict = collection_items_dict[key.rpartition("/")[2]]
            item_key = item_dict["meta"]["creatorSummary"] + " " + item_dict["meta"]["parsedDate"]
        except: 
            try:
                item_key = item_dict["data"]["title"]
            except:
                item_key = ""
        item_key = re.sub(r"(\d{4})-(\d+)\-(\d+)", r"\1", item_key)
        citation_keys_pairs[item_key] = key

In [32]:
citation_keys_pairs

{'Lowndes et al. 2017': '7109337/8C5W7WYE',
 'Scheidel 2018': '7109337/3J5XSHJ2',
 'Huggett 2017': '7109337/CY54CMQ9',
 'Huggett 2016': '7109337/QZV4FHQ6',
 'Raymond 2001': '7109337/3NH6EHMA',
 'Iversen 2007': '7109337/CAJ8RP6I',
 'Sherratt 2019': '7109337/GZXS5Q8K',
 'Madzharov 2009': '7109337/XDAURK5G',
 'Hollenstein 1975': '7109337/7DY6HUZB',
 'Duncan-Jones 2018': '7109337/J6GWZWL4',
 'Duncan-Jones 1990': '7109337/YFQQLVBK',
 'Duncan-Jones 1996': '7109337/HCU3WEJB',
 'Tahmasebi and Hengchen 2019': '7109337/UH4L3837',
 'Wilson 2009': '7109337/TARVRY26',
 'Liuzzo 2019': '7109337/WRRYLBT4',
 'Wilkinson et al. 2016': '7109337/VI7N28PJ',
 'Ballsun-Stanton 2020': '7109337/KGBLD6FY',
 'Kolb 2019': '7109337/MCUQLXCG',
 'Ober 2015': '7109337/RB28J3CE',
 'Morris 2010': '7109337/TGQ9TAPF',
 'Morris 2013': '7109337/93X7WDDV',
 'Hanson et al. 2017': '7109337/WZ6MD9YX',
 'Mullins et al. 2018': '7109337/2ASLDCJP',
 'Borgman 2015': '7109337/FBAWXZ3I',
 'Cayless et al. 2010': '7109337/EYTI8IQA',
 'L

# Small test

this way, we can easily generate the data in the form produced by cite2c, combining **collection ID** and **item ID**. 

However, it seems that cite2c does not support group collection. We need to work with our personal collection instead.

Here we test how the citations work. We will use Wilson 2012 as an example. Let put it here <cite data-cite="1913534/SYSTIFZQ"></cite>. Another citation would be here <cite data-cite="1913534/627JE7WX"></cite> or here <cite data-cite="1913534/IFEXKMWT"></cite> (here should be Mullins et al. 2018 - but does not render automatically). <cite data-cite="1913534/MUKI9YSZ"></cite>

insert citation here <cite data-cite="undefined"></cite>.

<cite data-cite="1913534/U48VTMSM"></cite>

<div class="cite2c-biblio"></div>

# Read ipynb as text file

<cite data-cite="1913534/U48VTMSM"></cite>

In [33]:
notebook_text = open("Digital_epigraphy.ipynb").read()
notebook_text[:1000]

'{\n "cells": [\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "title"\n    ]\n   },\n   "source": [\n    "# Inscriptions as data: digital epigraphy in macro-historical perspective "\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "contributor"\n    ]\n   },\n   "source": [\n    "### Petra Hermankova\\n",\n    "Author. Aarhus University, [ORCID: 0000-0002-6349-0540](https://orcid.org/0000-0002-6349-0540)"\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "contributor"\n    ]\n   },\n   "source": [\n    "### Vojtech Kase\\n",\n    "Author. Aarhus University, [ORCID: 0000-0002-6601-1605](http://orcid.org/0000-0002-6601-1605)"\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "contributor"\n    ]\n   },\n   "source": [\n    "### Adela Sobotkova\\n",\n    "Author. Aarhus University, [ORCID:0000-0002-4541-3963](https://orcid.org/0000-0002-4541-3963)"\n   ]\n  

In [34]:
for key in citation_keys_pairs.keys():
    if key in notebook_text:
        print(key, citation_keys_pairs[key])

Lowndes et al. 2017 7109337/8C5W7WYE
Scheidel 2018 7109337/3J5XSHJ2
Huggett 2017 7109337/CY54CMQ9
Raymond 2001 7109337/3NH6EHMA
Iversen 2007 7109337/CAJ8RP6I
Sherratt 2019 7109337/GZXS5Q8K
Madzharov 2009 7109337/XDAURK5G
Hollenstein 1975 7109337/7DY6HUZB
Duncan-Jones 2018 7109337/J6GWZWL4
Duncan-Jones 1990 7109337/YFQQLVBK
Duncan-Jones 1996 7109337/HCU3WEJB
Tahmasebi and Hengchen 2019 7109337/UH4L3837
Wilson 2009 7109337/TARVRY26
Liuzzo 2019 7109337/WRRYLBT4
Wilkinson et al. 2016 7109337/VI7N28PJ
Kolb 2019 7109337/MCUQLXCG
Ober 2015 7109337/RB28J3CE
Morris 2010 7109337/TGQ9TAPF
Hanson et al. 2017 7109337/WZ6MD9YX
Mullins et al. 2018 7109337/2ASLDCJP
Borgman 2015 7109337/FBAWXZ3I
Cayless et al. 2010 7109337/EYTI8IQA
Laurence 1999 7109337/QSJYQVZZ
Bodard 2008 7109337/KE9T4566
Bodard et al. 2021 7109337/2KEXYJLP
Avanzini et al. 2018 7109337/7EHKTWQD
Liuzzo 2018 7109337/TKXWFLYN
Harper 2016 7109337/SVYA23ZT
Verhagen 2019 7109337/BG7SH7C4
De Santis and Rossi 2018 7109337/NKKHMIDW
Wilson and

Working at the level of the province with a couple thousand inscriptions at a time, scholars have started constructing regional diachronic overviews of epigraphic production. Comparative studies between North Africa, Gaul or Greece revealed that epigraphic production in these provinces follows the same diachronic pattern. Inscription numbers peak at the end of the second century AD, during the reign of Septimius Severus (AD 193 - AD 211), and decline abruptly in the beginning of the third century AD (MacMullen 1982; Meyer 1991; Woolf 1996). Researchers started exploring different drivers for such convergence, interrogating the role of funerary habits to the popularity of public status display to the democratisation of citizenship. For instance, Elizabeth Meyer used the example of epitaphs to explain the drop in the number of inscriptions after the Constitutio Antoniniana in AD 212 granted Roman citizenship to all inhabitants of the Roman Empire. According to Meyer, being a Roman citizen lost some of its prestige and so did funerary inscriptions as public markers of societal status (Meyer 1990, 78-81). Such explanations failed to address the phenomenon of epigraphic production in all its breadth and complexity, focusing only on funerary inscriptions from selected regions. Since the time of MacMullen many scholars have attempted to study epigraphic production at the scale of the Empire (e.g., Hedrick 1999; Trout 2009; Beltran Lloris 2014; Bolle, Machado, and Witschel 2017; Nawotka 2021; Blanco Perez 2021). These efforts have been hindered first by the constraints on interoperability and integration of digital datasets, second, by the volume and diversity of epigraphic data, and finally, by the inability to precisely quantify the number of inscriptions at any point in time (Beltran Lloris 2014, 139).

In [35]:
test_paragraph = "Working at the level of the province with a couple thousand inscriptions at a time, scholars have started constructing regional diachronic overviews of epigraphic production. Comparative studies between North Africa, Gaul or Greece revealed that epigraphic production in these provinces follows the same diachronic pattern. Inscription numbers peak at the end of the second century AD, during the reign of Septimius Severus (AD 193 - AD 211), and decline abruptly in the beginning of the third century AD (MacMullen 1982; Meyer 1991; Woolf 1996). Researchers started exploring different drivers for such convergence, interrogating the role of funerary habits to the popularity of public status display to the democratisation of citizenship. For instance, Elizabeth Meyer used the example of epitaphs to explain the drop in the number of inscriptions after the Constitutio Antoniniana in AD 212 granted Roman citizenship to all inhabitants of the Roman Empire. According to Meyer, being a Roman citizen lost some of its prestige and so did funerary inscriptions as public markers of societal status (Meyer 1990, 78-81). Such explanations failed to address the phenomenon of epigraphic production in all its breadth and complexity, focusing only on funerary inscriptions from selected regions. Since the time of MacMullen many scholars have attempted to study epigraphic production at the scale of the Empire (e.g., Hedrick 1999; Trout 2009; Beltran Lloris 2014; Bolle, Machado, and Witschel 2017; Nawotka 2021; Blanco Perez 2021). These efforts have been hindered first by the constraints on interoperability and integration of digital datasets, second, by the volume and diversity of epigraphic data, and finally, by the inability to precisely quantify the number of inscriptions at any point in time (Beltran Lloris 2014, 139)."
print(test_paragraph)

Working at the level of the province with a couple thousand inscriptions at a time, scholars have started constructing regional diachronic overviews of epigraphic production. Comparative studies between North Africa, Gaul or Greece revealed that epigraphic production in these provinces follows the same diachronic pattern. Inscription numbers peak at the end of the second century AD, during the reign of Septimius Severus (AD 193 - AD 211), and decline abruptly in the beginning of the third century AD (MacMullen 1982; Meyer 1991; Woolf 1996). Researchers started exploring different drivers for such convergence, interrogating the role of funerary habits to the popularity of public status display to the democratisation of citizenship. For instance, Elizabeth Meyer used the example of epitaphs to explain the drop in the number of inscriptions after the Constitutio Antoniniana in AD 212 granted Roman citizenship to all inhabitants of the Roman Empire. According to Meyer, being a Roman citize

In [36]:
citations

{'7109337/5DKTH37I': {'type': 'article',
  'title': 'Full Text',
  'URL': 'https://www.nature.com/articles/s41559-017-0160.pdf',
  'accessed': {'date-parts': [[2021, 6, 11]]}},
 '7109337/8C5W7WYE': {'type': 'article-journal',
  'title': 'Our path to better science in less time using open data science tools',
  'container-title': 'Nature Ecology & Evolution',
  'page': '0160',
  'volume': '1',
  'issue': '6',
  'URL': 'http://www.nature.com/articles/s41559-017-0160',
  'DOI': '10.1038/s41559-017-0160',
  'journalAbbreviation': 'Nat Ecol Evol',
  'language': 'en',
  'author': [{'family': 'Lowndes', 'given': 'Julia S. Stewart'},
   {'family': 'Best', 'given': 'Benjamin D.'},
   {'family': 'Scarborough', 'given': 'Courtney'},
   {'family': 'Afflerbach', 'given': 'Jamie C.'},
   {'family': 'Frazier', 'given': 'Melanie R.'},
   {'family': 'O’Hara', 'given': 'Casey C.'},
   {'family': 'Jiang', 'given': 'Ning'},
   {'family': 'Halpern', 'given': 'Benjamin S.'}],
  'issued': {'date-parts': [['2

In [37]:
test_paragraph = "Working at the level of the province with a couple thousand inscriptions at a time, scholars have started constructing regional diachronic overviews of epigraphic production. Comparative studies between North Africa, Gaul or Greece revealed that epigraphic production in these provinces follows the same diachronic pattern. Inscription numbers peak at the end of the second century AD, during the reign of Septimius Severus (AD 193 - AD 211), and decline abruptly in the beginning of the third century AD (MacMullen 1982; Meyer 1991; Woolf 1996). Researchers started exploring different drivers for such convergence, interrogating the role of funerary habits to the popularity of public status display to the democratisation of citizenship. For instance, Elizabeth Meyer used the example of epitaphs to explain the drop in the number of inscriptions after the Constitutio Antoniniana in AD 212 granted Roman citizenship to all inhabitants of the Roman Empire. According to Meyer, being a Roman citizen lost some of its prestige and so did funerary inscriptions as public markers of societal status (Meyer 1990, 78-81). Such explanations failed to address the phenomenon of epigraphic production in all its breadth and complexity, focusing only on funerary inscriptions from selected regions. Since the time of MacMullen many scholars have attempted to study epigraphic production at the scale of the Empire (e.g., Hedrick 1999; Trout 2009; Beltran Lloris 2014; Bolle, Machado, and Witschel 2017; Nawotka 2021; Blanco Perez 2021). These efforts have been hindered first by the constraints on interoperability and integration of digital datasets, second, by the volume and diversity of epigraphic data, and finally, by the inability to precisely quantify the number of inscriptions at any point in time (Beltran Lloris 2014, 139)."
citations_used = {}
for key in citation_keys_pairs.keys():
    if key in test_paragraph:
        print(key)
        citations_used[citation_keys_pairs[key]] = citations[citation_keys_pairs[key]]
        test_paragraph = test_paragraph.replace(key, '<cite data-cite="' + citation_keys_pairs[key] + '"></cite>')

Hedrick 1999
Nawotka 2021
Meyer 1990
MacMullen 1982
Woolf 1996
Trout 2009


In [38]:
citations_used

{'7109337/IRUVQAYJ': {'type': 'article-journal',
  'title': 'Democracy and the Athenian Epigraphical Habit',
  'container-title': 'Hesperia',
  'page': '387-439',
  'volume': '68',
  'issue': '3',
  'URL': 'http://links.jstor.org/sici?sici=0018-098X%28199907%2F09%2968%3A3%3C387%3ADATAEH%3E2.0.CO%3B2-J&origin=crossref',
  'DOI': '10.2307/148494',
  'journalAbbreviation': 'Hesperia',
  'language': 'en',
  'author': [{'family': 'Hedrick', 'given': 'Charles W. Jr.'}],
  'issued': {'date-parts': [[1999]]},
  'accessed': {'date-parts': [[2019, 11, 21]]}},
 '7109337/TXCY5XL8': {'type': 'book',
  'title': 'Epigraphic Culture in the Eastern Mediterranean in Antiquity',
  'publisher': 'Routledge',
  'edition': '1',
  'URL': 'https://www.taylorfrancis.com/books/9781000164800',
  'ISBN': '978-1-00-302530-6',
  'note': 'DOI: 10.4324/9781003025306',
  'language': 'en',
  'editor': [{'family': 'Nawotka', 'given': 'Krzysztof'}],
  'issued': {'date-parts': [[2021]]},
  'accessed': {'date-parts': [[2021

In [40]:
test_paragraph

'Working at the level of the province with a couple thousand inscriptions at a time, scholars have started constructing regional diachronic overviews of epigraphic production. Comparative studies between North Africa, Gaul or Greece revealed that epigraphic production in these provinces follows the same diachronic pattern. Inscription numbers peak at the end of the second century AD, during the reign of Septimius Severus (AD 193 - AD 211), and decline abruptly in the beginning of the third century AD (<cite data-cite="7109337/C5QVR3SE"></cite>; Meyer 1991; <cite data-cite="7109337/A6W7Q3HZ"></cite>). Researchers started exploring different drivers for such convergence, interrogating the role of funerary habits to the popularity of public status display to the democratisation of citizenship. For instance, Elizabeth Meyer used the example of epitaphs to explain the drop in the number of inscriptions after the Constitutio Antoniniana in AD 212 granted Roman citizenship to all inhabitants 

Working at the level of the province with a couple thousand inscriptions at a time, scholars have started constructing regional diachronic overviews of epigraphic production. Comparative studies between North Africa, Gaul or Greece revealed that epigraphic production in these provinces follows the same diachronic pattern. Inscription numbers peak at the end of the second century AD, during the reign of Septimius Severus (AD 193 - AD 211), and decline abruptly in the beginning of the third century AD (<cite data-cite="1913534/BGNB6HUT"></cite>; Meyer 1991; <cite data-cite="1913534/HBPZKHXT"></cite>). Researchers started exploring different drivers for such convergence, interrogating the role of funerary habits to the popularity of public status display to the democratisation of citizenship. For instance, Elizabeth Meyer used the example of epitaphs to explain the drop in the number of inscriptions after the Constitutio Antoniniana in AD 212 granted Roman citizenship to all inhabitants of the Roman Empire. According to Meyer, being a Roman citizen lost some of its prestige and so did funerary inscriptions as public markers of societal status (<cite data-cite="1913534/MUKI9YSZ"></cite>, 78-81). Such explanations failed to address the phenomenon of epigraphic production in all its breadth and complexity, focusing only on funerary inscriptions from selected regions. Since the time of MacMullen many scholars have attempted to study epigraphic production at the scale of the Empire (e.g., <cite data-cite="1913534/2LT8WIGC"></cite>; <cite data-cite="1913534/F3Y2FVVY"></cite>; Beltran Lloris 2014; Bolle, Machado, and Witschel 2017; <cite data-cite="1913534/NEGLBLPH"></cite>; Blanco Perez 2021). These efforts have been hindered first by the constraints on interoperability and integration of digital datasets, second, by the volume and diversity of epigraphic data, and finally, by the inability to precisely quantify the number of inscriptions at any point in time (Beltran Lloris 2014, 139).



In [41]:
import json

In [42]:
notebook_dict = json.loads(notebook_text)
notebook_dict["metadata"]["cite2c"]["citations"]

{'7109337/2ASLDCJP': {'DOI': '10.1177/0003122418772567',
  'URL': 'http://journals.sagepub.com/doi/10.1177/0003122418772567',
  'abstract': 'Proponents of the Axial Age contend that parallel cultural developments between 800 and 200 BCE in what is today China, Greece, India, Iran, and Israel-Palestine constitute the global historical turning point toward modernity. The Axial Age concept is well-known and influential, but deficiencies in the historical evidence and sociological analysis available have thwarted efforts to evaluate the concept’s major global contentions. As a result, the Axial Age concept remains controversial. Seshat: Global History Databank provides new tools for examining this topic in social formations across Afro-Eurasia during the first two millennia BCE and first millennium CE, allowing scholars to empirically evaluate the varied and contrasting claims researchers have put forward. Results undercut the notion of a specific “age” of axiality limited to a specific ge

In [43]:
notebook_dict["cells"][10:20]

[{'cell_type': 'code',
  'execution_count': 3,
  'metadata': {'tags': ['configuration', 'Python', 'hermeneutics']},
  'outputs': [{'name': 'stderr',
    'output_type': 'stream',
    'text': ['Matplotlib is building the font cache; this may take a moment.\n']}],
  'source': ['import geopandas as gpd\n',
   'import cite2c\n',
   'import requests\n',
   'import seaborn as sns\n',
   'import matplotlib.colors as mcolors\n',
   'import matplotlib.pyplot as plt\n',
   'from scipy.stats import trapz\n',
   'import scipy\n',
   'import nltk\n',
   'import json\n',
   'import tempun\n',
   'import sddk\n',
   'import numpy as np\n',
   'import pandas as pd\n',
   'pd.options.display.max_columns = 1000  # to see all columns']},
 {'cell_type': 'code',
  'execution_count': 4,
  'metadata': {'tags': ['configuration', 'hermeneutics']},
  'outputs': [{'name': 'stdout',
    'output_type': 'stream',
    'text': ['Requirement already satisfied: cite2c in /opt/conda/lib/python3.7/site-packages (0.2.1)\n'

In [44]:
notebook_text = open("Digital_epigraphy.ipynb").read()
notebook_text[:1000]

'{\n "cells": [\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "title"\n    ]\n   },\n   "source": [\n    "# Inscriptions as data: digital epigraphy in macro-historical perspective "\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "contributor"\n    ]\n   },\n   "source": [\n    "### Petra Hermankova\\n",\n    "Author. Aarhus University, [ORCID: 0000-0002-6349-0540](https://orcid.org/0000-0002-6349-0540)"\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "contributor"\n    ]\n   },\n   "source": [\n    "### Vojtech Kase\\n",\n    "Author. Aarhus University, [ORCID: 0000-0002-6601-1605](http://orcid.org/0000-0002-6601-1605)"\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "contributor"\n    ]\n   },\n   "source": [\n    "### Adela Sobotkova\\n",\n    "Author. Aarhus University, [ORCID:0000-0002-4541-3963](https://orcid.org/0000-0002-4541-3963)"\n   ]\n  

In [45]:
citations_used = {}
for key in citation_keys_pairs.keys():
    if key in notebook_text:
        citations_used[citation_keys_pairs[key]] = citations[citation_keys_pairs[key]]
        notebook_text = notebook_text.replace(key, "<cite data-cite=\'" + citation_keys_pairs[key] + "\'></cite>")

In [46]:
notebook_dict = json.loads(notebook_text)
notebook_dict["metadata"]["cite2c"]["citations"] = citations_used

In [47]:
with open("Digital_epigraphy_cite2c_test_2.ipynb", "w") as f:
    json.dump(notebook_dict, f)