In [2]:
!pip install pyzotero sddk -U
import requests
import sddk

In [3]:
s = sddk.cloudSession("sciencedata.dk")

Your ScienceData username (e.g. '123456@au.dk'): 648560@au.dk
Your ScienceData password: ········
endpoint variable has been configured to: https://sciencedata.dk/files/


In [4]:
# based on https://pyzotero.readthedocs.io/en/latest/

zot_keys = s.read_file("zot_keys.json", "dict")
library_id =  zot_keys["user_id"] # or: getpass.getpass("insert your id: ")
api_key =  zot_keys["key"] # or: getpass.getpass("insert your key: ")

# base url for individual user library
base_url = "https://api.zotero.org/users/" + str(library_id) + "/"
headers ={"Authorization": "Bearer " + api_key}

file has not been found; check filename and path.


TypeError: 'NoneType' object is not subscriptable

In [4]:
# list all personal collections
url = "https://api.zotero.org/users/2132694/collections"
resp = requests.get(url, headers=headers)
resp.json()

[{'key': 'P55PUAIK',
  'version': 2818,
  'library': {'type': 'user',
   'id': 2132694,
   'name': 'vojtech.kase',
   'links': {'alternate': {'href': 'https://www.zotero.org/vojtech.kase',
     'type': 'text/html'}}},
  'links': {'self': {'href': 'https://api.zotero.org/users/2132694/collections/P55PUAIK',
    'type': 'application/json'},
   'alternate': {'href': 'https://www.zotero.org/vojtech.kase/collections/P55PUAIK',
    'type': 'text/html'}},
  'meta': {'numCollections': 0, 'numItems': 62},
  'data': {'key': 'P55PUAIK',
   'version': 2818,
   'name': 'JDH_article',
   'parentCollection': False,
   'relations': {'owl:sameAs': 'http://zotero.org/groups/2366083/collections/QR9UH9RG'}}}]

In [5]:
# list all items within preselected collection:
url = "https://api.zotero.org/users/2132694/collections/P55PUAIK/items?limit=1000"
resp = requests.get(url, headers=headers)

In [6]:
# ids of items
citation_keys_pairs = {}
for item in resp.json():
    try:
        item_key = item["meta"]["creatorSummary"] + " " + item["meta"]["parsedDate"]
    except: 
        try:
            item_key = item["data"]["title"]
        except:
            pass
    citation_keys_pairs[item_key] = item["data"]["key"]

In [7]:
citation_keys_pairs

{'Full Text': '49AE839R',
 'Accepted Version': 'I4SY879G',
 'Wilson_2012_City Sizes and Urbanization in the Roman Empire.pdf': 'AGSJ79AY',
 'Attachment': 'YAFN5N27',
 'Hedrick - 1999 - Democracy and the Athenian Epigraphical Habit.pdf': 'TVCGWGMN',
 'Crema2020_JomonPopulationDynamics.pdf': 'MG4AUE6B',
 'PDF': 'Z8JVQ5FX',
 'Crema - 2012 - Modelling Temporal Uncertainty in Archaeological A.pdf': 'VDPSKXF2',
 'Turchin_Scheidel_2009_Coin Hoards Speak of Population Declines in Ancient Rome.pdf': 'K5B59T6I',
 'turchin-et-al_2018_quantitative-historical-analysis.pdf': 'IJPUN3PC',
 'Ballsun-Stanton 2020': 'P79KQAFU',
 'Wilson 2012': 'SYSTIFZQ',
 'Hanson et al. 2017': 'C2MUHDNG',
 'Morris 2013': '9YX6ZS7N',
 'Morris 2010': '627JE7WX',
 'Mullins et al. 2018': 'IFEXKMWT',
 'Harper 2016': '33TNUAZ3',
 'Kolb 2019-06-17': '95I2Q54Z',
 'Borgman 2015': 'GSAVHWAN',
 'Cayless et al. 2010-12-31': 'KRXAF9YL',
 'Laurence 1999': 'AW6LP4AP',
 'Bodard 2008': '66WIWW57',
 'Liuzzo 2018-12-31': '4WT5APEZ',
 'de 

# Small test

this way, we can easily generate the data in the form produced by cite2c, combining **collection ID** and **item ID**. 

However, it seems that cite2c does not support group collection. We need to work with our personal collection instead.

Here we test how the citations work. We will use Wilson 2012 as an example. Let put it here <cite data-cite="1913534/SYSTIFZQ"></cite>. Another citation would be here <cite data-cite="1913534/627JE7WX"></cite> or here <cite data-cite="1913534/IFEXKMWT"></cite> (here should be Mullins et al. 2018 - but does not render automatically) 

<cite data-cite="1913534/U48VTMSM"></cite>

<div class="cite2c-biblio"></div>

# Read ipynb as text file

<cite data-cite="1913534/U48VTMSM"></cite>

In [8]:
notebook_text = open("Digital_epigraphy.ipynb").read()
notebook_text[:1000]

'{\n "cells": [\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "title"\n    ]\n   },\n   "source": [\n    "# Inscriptions as data: digital epigraphy in macro-historical perspective "\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "contributor"\n    ]\n   },\n   "source": [\n    "### Petra Hermankova\\n",\n    "Author. Aarhus University, [ORCID: 0000-0002-6349-0540](https://orcid.org/0000-0002-6349-0540)"\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "contributor"\n    ]\n   },\n   "source": [\n    "### Vojtech Kase\\n",\n    "Author. Aarhus University, [ORCID: 0000-0002-6601-1605](http://orcid.org/0000-0002-6601-1605)"\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "contributor"\n    ]\n   },\n   "source": [\n    "### Adela Sobotkova\\n",\n    "Author. Aarhus University, [ORCID:0000-0002-4541-3963](https://orcid.org/0000-0002-4541-3963)"\n   ]\n  

In [9]:
for key in citation_keys_pairs.keys():
    if key in notebook_text:
        print(key)

PDF
Wilson 2012
Hanson et al. 2017
Mullins et al. 2018
Harper 2016
Borgman 2015
Laurence 1999
Bodard 2008
Verhagen 2019
Bodel 2001
Crema and Kobayashi 2020
Verhagen et al. 2016
Bowman and Wilson 2009
Turchin and Scheidel 2009
Hedrick 1999
Nawotka 2021
MacMullen 1982
Trout 2009
Feraudi-Gruénais and Grieshaber 2016
Grieshaber 2019
Woolf 1996
Meyer 1990
Dow 1969
Bloch 1947
Prag 2002
Crema 2012
Johnson 2004
Oksanen and Lewis 2020
Turchin et al. 2018


Working at the level of the province with a couple thousand inscriptions at a time, scholars have started constructing regional diachronic overviews of epigraphic production. Comparative studies between North Africa, Gaul or Greece revealed that epigraphic production in these provinces follows the same diachronic pattern. Inscription numbers peak at the end of the second century AD, during the reign of Septimius Severus (AD 193 - AD 211), and decline abruptly in the beginning of the third century AD (MacMullen 1982; Meyer 1991; Woolf 1996). Researchers started exploring different drivers for such convergence, interrogating the role of funerary habits to the popularity of public status display to the democratisation of citizenship. For instance, Elizabeth Meyer used the example of epitaphs to explain the drop in the number of inscriptions after the Constitutio Antoniniana in AD 212 granted Roman citizenship to all inhabitants of the Roman Empire. According to Meyer, being a Roman citizen lost some of its prestige and so did funerary inscriptions as public markers of societal status (Meyer 1990, 78-81). Such explanations failed to address the phenomenon of epigraphic production in all its breadth and complexity, focusing only on funerary inscriptions from selected regions. Since the time of MacMullen many scholars have attempted to study epigraphic production at the scale of the Empire (e.g., Hedrick 1999; Trout 2009; Beltran Lloris 2014; Bolle, Machado, and Witschel 2017; Nawotka 2021; Blanco Perez 2021). These efforts have been hindered first by the constraints on interoperability and integration of digital datasets, second, by the volume and diversity of epigraphic data, and finally, by the inability to precisely quantify the number of inscriptions at any point in time (Beltran Lloris 2014, 139).

In [10]:
test_paragraph = "Working at the level of the province with a couple thousand inscriptions at a time, scholars have started constructing regional diachronic overviews of epigraphic production. Comparative studies between North Africa, Gaul or Greece revealed that epigraphic production in these provinces follows the same diachronic pattern. Inscription numbers peak at the end of the second century AD, during the reign of Septimius Severus (AD 193 - AD 211), and decline abruptly in the beginning of the third century AD (MacMullen 1982; Meyer 1991; Woolf 1996). Researchers started exploring different drivers for such convergence, interrogating the role of funerary habits to the popularity of public status display to the democratisation of citizenship. For instance, Elizabeth Meyer used the example of epitaphs to explain the drop in the number of inscriptions after the Constitutio Antoniniana in AD 212 granted Roman citizenship to all inhabitants of the Roman Empire. According to Meyer, being a Roman citizen lost some of its prestige and so did funerary inscriptions as public markers of societal status (Meyer 1990, 78-81). Such explanations failed to address the phenomenon of epigraphic production in all its breadth and complexity, focusing only on funerary inscriptions from selected regions. Since the time of MacMullen many scholars have attempted to study epigraphic production at the scale of the Empire (e.g., Hedrick 1999; Trout 2009; Beltran Lloris 2014; Bolle, Machado, and Witschel 2017; Nawotka 2021; Blanco Perez 2021). These efforts have been hindered first by the constraints on interoperability and integration of digital datasets, second, by the volume and diversity of epigraphic data, and finally, by the inability to precisely quantify the number of inscriptions at any point in time (Beltran Lloris 2014, 139)."
print(test_paragraph)

Working at the level of the province with a couple thousand inscriptions at a time, scholars have started constructing regional diachronic overviews of epigraphic production. Comparative studies between North Africa, Gaul or Greece revealed that epigraphic production in these provinces follows the same diachronic pattern. Inscription numbers peak at the end of the second century AD, during the reign of Septimius Severus (AD 193 - AD 211), and decline abruptly in the beginning of the third century AD (MacMullen 1982; Meyer 1991; Woolf 1996). Researchers started exploring different drivers for such convergence, interrogating the role of funerary habits to the popularity of public status display to the democratisation of citizenship. For instance, Elizabeth Meyer used the example of epitaphs to explain the drop in the number of inscriptions after the Constitutio Antoniniana in AD 212 granted Roman citizenship to all inhabitants of the Roman Empire. According to Meyer, being a Roman citize

In [11]:
for key in citation_keys_pairs.keys():
    if key in test_paragraph:
        test_paragraph = test_paragraph.replace(key, '<cite data-cite="1913534/' + citation_keys_pairs[key] + '"></cite>')

In [12]:
test_paragraph

'Working at the level of the province with a couple thousand inscriptions at a time, scholars have started constructing regional diachronic overviews of epigraphic production. Comparative studies between North Africa, Gaul or Greece revealed that epigraphic production in these provinces follows the same diachronic pattern. Inscription numbers peak at the end of the second century AD, during the reign of Septimius Severus (AD 193 - AD 211), and decline abruptly in the beginning of the third century AD (<cite data-cite="1913534/BGNB6HUT"></cite>; Meyer 1991; <cite data-cite="1913534/HBPZKHXT"></cite>). Researchers started exploring different drivers for such convergence, interrogating the role of funerary habits to the popularity of public status display to the democratisation of citizenship. For instance, Elizabeth Meyer used the example of epitaphs to explain the drop in the number of inscriptions after the Constitutio Antoniniana in AD 212 granted Roman citizenship to all inhabitants 

Working at the level of the province with a couple thousand inscriptions at a time, scholars have started constructing regional diachronic overviews of epigraphic production. Comparative studies between North Africa, Gaul or Greece revealed that epigraphic production in these provinces follows the same diachronic pattern. Inscription numbers peak at the end of the second century AD, during the reign of Septimius Severus (AD 193 - AD 211), and decline abruptly in the beginning of the third century AD (<cite data-cite="1913534/BGNB6HUT"></cite>; Meyer 1991; <cite data-cite="1913534/HBPZKHXT"></cite>). Researchers started exploring different drivers for such convergence, interrogating the role of funerary habits to the popularity of public status display to the democratisation of citizenship. For instance, Elizabeth Meyer used the example of epitaphs to explain the drop in the number of inscriptions after the Constitutio Antoniniana in AD 212 granted Roman citizenship to all inhabitants of the Roman Empire. According to Meyer, being a Roman citizen lost some of its prestige and so did funerary inscriptions as public markers of societal status (<cite data-cite="1913534/MUKI9YSZ"></cite>, 78-81). Such explanations failed to address the phenomenon of epigraphic production in all its breadth and complexity, focusing only on funerary inscriptions from selected regions. Since the time of MacMullen many scholars have attempted to study epigraphic production at the scale of the Empire (e.g., <cite data-cite="1913534/2LT8WIGC"></cite>; <cite data-cite="1913534/F3Y2FVVY"></cite>; Beltran Lloris 2014; Bolle, Machado, and Witschel 2017; <cite data-cite="1913534/NEGLBLPH"></cite>; Blanco Perez 2021). These efforts have been hindered first by the constraints on interoperability and integration of digital datasets, second, by the volume and diversity of epigraphic data, and finally, by the inability to precisely quantify the number of inscriptions at any point in time (Beltran Lloris 2014, 139).

