In [1]:
#!pip install pyzotero
import requests
import sddk
import getpass

# Zotero API configuration

1. find your zotero user ID and insert it interactively in the cell below (you can find it e.g. from https://www.zotero.org/settings/keys)

In [2]:
userID = input("Paste your Zotero user ID: ")

Paste your Zotero user ID: 2132694


2. go to https://www.zotero.org/settings/keys
3. `Create new private key`
4. name your key in `Key description`, e.g. `pyzot`.
5. click at `Save Key`
6. copy the generated key into clipboard
7 insert it in the cell below

In [3]:
api_key =  getpass.getpass("Paste your key: ")

Paste your key: ········


In [4]:
# prepare the authorization
base_url = "https://api.zotero.org/users/" + str(userID) + "/"
headers ={"Authorization": "Bearer " + api_key}

In [5]:
# list all personal collections
url = "https://api.zotero.org/users/2132694/collections"
resp = requests.get(url, headers=headers)
resp.json()

[{'key': 'P55PUAIK',
  'version': 2818,
  'library': {'type': 'user',
   'id': 2132694,
   'name': 'vojtech.kase',
   'links': {'alternate': {'href': 'https://www.zotero.org/vojtech.kase',
     'type': 'text/html'}}},
  'links': {'self': {'href': 'https://api.zotero.org/users/2132694/collections/P55PUAIK',
    'type': 'application/json'},
   'alternate': {'href': 'https://www.zotero.org/vojtech.kase/collections/P55PUAIK',
    'type': 'text/html'}},
  'meta': {'numCollections': 0, 'numItems': 62},
  'data': {'key': 'P55PUAIK',
   'version': 2818,
   'name': 'JDH_article',
   'parentCollection': False,
   'relations': {'owl:sameAs': 'http://zotero.org/groups/2366083/collections/QR9UH9RG'}}}]

Among these collections, find the one you want to use and copy its `key` (i.e. the value of the `key` attribute. 

In [6]:
collection_key = input("your collection key: ")

your collection key: P55PUAIK


In [7]:
# list all items within preselected collection:
url = "https://api.zotero.org/users/2132694/collections/" + collection_key + "/items?limit=1000"
collection_items_json = requests.get(url, headers=headers).json()

In [8]:
# inspect the items
collection_items_json

[{'key': '4DU2BY28',
  'version': 2829,
  'library': {'type': 'user',
   'id': 2132694,
   'name': 'vojtech.kase',
   'links': {'alternate': {'href': 'https://www.zotero.org/vojtech.kase',
     'type': 'text/html'}}},
  'links': {'self': {'href': 'https://api.zotero.org/users/2132694/items/4DU2BY28',
    'type': 'application/json'},
   'alternate': {'href': 'https://www.zotero.org/vojtech.kase/items/4DU2BY28',
    'type': 'text/html'},
   'up': {'href': 'https://api.zotero.org/users/2132694/items/C2MUHDNG',
    'type': 'application/json'}},
  'meta': {'numChildren': False},
  'data': {'key': '4DU2BY28',
   'version': 2829,
   'parentItem': 'C2MUHDNG',
   'itemType': 'attachment',
   'linkMode': 'imported_url',
   'title': 'Full Text',
   'accessDate': '2021-05-18T11:04:52Z',
   'url': 'https://royalsocietypublishing.org/doi/pdf/10.1098/rsif.2017.0367',
   'note': '',
   'contentType': 'application/pdf',
   'charset': '',
   'filename': 'Hanson et al. - 2017 - Urbanism and the division 

In [13]:
# ids of items
citation_keys_pairs = {}
for item in collection_items_json:
    if item["data"]["itemType"] != "attachment":
        try:
            item_key = item["meta"]["creatorSummary"] + " " + item["meta"]["parsedDate"]
        except: 
            try:
                item_key = item["data"]["title"]
            except:
                item_key = ""
        citation_keys_pairs[item_key] = item["data"]["key"]

In [14]:
citation_keys_pairs

{'Ballsun-Stanton 2020': '5MY4KSUI',
 'Wilson 2012': 'SYSTIFZQ',
 'Hanson et al. 2017': 'C2MUHDNG',
 'Morris 2013': '9YX6ZS7N',
 'Morris 2010': '627JE7WX',
 'Mullins et al. 2018': 'IFEXKMWT',
 'Harper 2016': '33TNUAZ3',
 'Kolb 2019-06-17': '95I2Q54Z',
 'Borgman 2015': 'GSAVHWAN',
 'Cayless et al. 2010-12-31': 'KRXAF9YL',
 'Laurence 1999': 'AW6LP4AP',
 'Bodard 2008': '66WIWW57',
 'Liuzzo 2018-12-31': '4WT5APEZ',
 'de Ligt and Tacoma 2016-01-19': '6ZEVHLM6',
 'Wilson and Flohr 2016-01-01': 'B99689HI',
 'Verhagen 2019': 'A2U4FIKT',
 'Hanel 2020-03-24': 'CLBZUHJ7',
 'Bodard et al. 2021-03-26': 'AHA9EWZL',
 'Avanzini et al. 2018-12-31': 'LFKD595C',
 'De Santis and Rossi 2018-12-31': '37N8YE3I',
 'Littman and Littman 1973': 'UZDY7HD7',
 'Rabinowitz et al. 2018-12-31': 'N8MU7LGT',
 'Bodel 2001': '4YVYEDQD',
 'Crema and Kobayashi 2020': 'DF62R52E',
 'Kaše 2021-03-31': 'MT2ZRZBH',
 'Kemkes 2020-03-24': 'AIJX7C5S',
 'Verhagen et al. 2016': 'XJBYYW4X',
 'Keppie 1991': 'V9UVGQX2',
 'Bowman and Wil

# Test with one item

In [15]:
item_id = "627JE7WX"
url = "https://api.zotero.org/users/2132694/items/" + item_id + "?format=csljson"
item_json = requests.get(url, headers=headers).json()
item_json

{'items': [{'id': '1913534/627JE7WX',
   'type': 'book',
   'title': 'Why the west rules - for now : the patterns of history, and what they reveal about the future',
   'publisher': 'Farrar, Straus and Giroux',
   'publisher-place': 'New York',
   'event-place': 'New York',
   'abstract': 'Summary: Archaeologist and historian Ian Morris explains that Western dominance is largely the result of the effects of geography on the everyday efforts of ordinary people as they deal with crises of resources, disease, migration, and climate. As geography and human ingenuity continue to interact, however, the world over the next hundred years will subsequently change in astonishing ways, transforming Western rule in the process.',
   'ISBN': '978-0-312-61169-9',
   'note': 'Publication Title: Why the west rules - for now : the patterns of history, and what they reveal about the future /',
   'language': 'eng',
   'author': [{'family': 'Morris', 'given': 'Ian'}],
   'issued': {'date-parts': [[2010]]

In [16]:
# list all items within preselected collection:
url = "https://api.zotero.org/users/2132694/collections/" + collection_key + "/items?limit=1000&format=csljson"
collection_items_csljson = requests.get(url, headers=headers).json()
collection_items_csljson["items"][:5]

[{'id': '1913534/4DU2BY28',
  'type': 'article',
  'title': 'Full Text',
  'URL': 'https://royalsocietypublishing.org/doi/pdf/10.1098/rsif.2017.0367',
  'accessed': {'date-parts': [[2021, 5, 18]]}},
 {'id': '1913534/FTDUBX6P',
  'type': 'article',
  'title': 'Accepted Version',
  'URL': 'https://ore.exeter.ac.uk/repository/bitstream/10871/36086/2/deleted_FINAL_submission.pdf',
  'accessed': {'date-parts': [[2021, 5, 17]]}},
 {'id': '1913534/L47JEQBH',
  'type': 'article',
  'title': 'Full Text',
  'URL': 'https://www.degruyter.com/document/doi/10.1515/9783110607208-018/pdf',
  'accessed': {'date-parts': [[2021, 5, 17]]}},
 {'id': '1913534/7JEU5M89',
  'type': 'article',
  'title': 'Full Text',
  'URL': 'https://www.degruyter.com/document/doi/10.1515/9783110607208-017/pdf',
  'accessed': {'date-parts': [[2021, 5, 14]]}},
 {'id': '1913534/AGSJ79AY',
  'type': 'article',
  'title': 'Wilson_2012_City Sizes and Urbanization in the Roman Empire.pdf'}]

In [17]:
citations = {}
for item in collection_items_csljson["items"]:
    try:
        citations[item["id"]] = item
        citations[item["id"]].pop("id", None)
    except:
        pass

In [18]:
citations

{'1913534/4DU2BY28': {'type': 'article',
  'title': 'Full Text',
  'URL': 'https://royalsocietypublishing.org/doi/pdf/10.1098/rsif.2017.0367',
  'accessed': {'date-parts': [[2021, 5, 18]]}},
 '1913534/FTDUBX6P': {'type': 'article',
  'title': 'Accepted Version',
  'URL': 'https://ore.exeter.ac.uk/repository/bitstream/10871/36086/2/deleted_FINAL_submission.pdf',
  'accessed': {'date-parts': [[2021, 5, 17]]}},
 '1913534/L47JEQBH': {'type': 'article',
  'title': 'Full Text',
  'URL': 'https://www.degruyter.com/document/doi/10.1515/9783110607208-018/pdf',
  'accessed': {'date-parts': [[2021, 5, 17]]}},
 '1913534/7JEU5M89': {'type': 'article',
  'title': 'Full Text',
  'URL': 'https://www.degruyter.com/document/doi/10.1515/9783110607208-017/pdf',
  'accessed': {'date-parts': [[2021, 5, 14]]}},
 '1913534/AGSJ79AY': {'type': 'article',
  'title': 'Wilson_2012_City Sizes and Urbanization in the Roman Empire.pdf'},
 '1913534/3LU29L3J': {'type': 'article',
  'title': 'Full Text',
  'URL': 'https

In [30]:
# list all items within preselected collection:
url = "https://api.zotero.org/users/2132694/collections/" + collection_key + "/items?limit=1000"
collection_items_rawjson = requests.get(url, headers=headers).json()
collection_items_rawjson[:5]

[{'key': '4DU2BY28',
  'version': 2829,
  'library': {'type': 'user',
   'id': 2132694,
   'name': 'vojtech.kase',
   'links': {'alternate': {'href': 'https://www.zotero.org/vojtech.kase',
     'type': 'text/html'}}},
  'links': {'self': {'href': 'https://api.zotero.org/users/2132694/items/4DU2BY28',
    'type': 'application/json'},
   'alternate': {'href': 'https://www.zotero.org/vojtech.kase/items/4DU2BY28',
    'type': 'text/html'},
   'up': {'href': 'https://api.zotero.org/users/2132694/items/C2MUHDNG',
    'type': 'application/json'}},
  'meta': {'numChildren': False},
  'data': {'key': '4DU2BY28',
   'version': 2829,
   'parentItem': 'C2MUHDNG',
   'itemType': 'attachment',
   'linkMode': 'imported_url',
   'title': 'Full Text',
   'accessDate': '2021-05-18T11:04:52Z',
   'url': 'https://royalsocietypublishing.org/doi/pdf/10.1098/rsif.2017.0367',
   'note': '',
   'contentType': 'application/pdf',
   'charset': '',
   'filename': 'Hanson et al. - 2017 - Urbanism and the division 

In [33]:
collection_items_dict = dict([(el["key"], el) for el in collection_items_rawjson])

In [36]:
collection_items_dict

{'4DU2BY28': {'key': '4DU2BY28',
  'version': 2829,
  'library': {'type': 'user',
   'id': 2132694,
   'name': 'vojtech.kase',
   'links': {'alternate': {'href': 'https://www.zotero.org/vojtech.kase',
     'type': 'text/html'}}},
  'links': {'self': {'href': 'https://api.zotero.org/users/2132694/items/4DU2BY28',
    'type': 'application/json'},
   'alternate': {'href': 'https://www.zotero.org/vojtech.kase/items/4DU2BY28',
    'type': 'text/html'},
   'up': {'href': 'https://api.zotero.org/users/2132694/items/C2MUHDNG',
    'type': 'application/json'}},
  'meta': {'numChildren': False},
  'data': {'key': '4DU2BY28',
   'version': 2829,
   'parentItem': 'C2MUHDNG',
   'itemType': 'attachment',
   'linkMode': 'imported_url',
   'title': 'Full Text',
   'accessDate': '2021-05-18T11:04:52Z',
   'url': 'https://royalsocietypublishing.org/doi/pdf/10.1098/rsif.2017.0367',
   'note': '',
   'contentType': 'application/pdf',
   'charset': '',
   'filename': 'Hanson et al. - 2017 - Urbanism and t

In [41]:
import re

In [44]:
re.match("(\d{4})-(\d+)\-(\d+)", "2018-07-08").groups()

('2018', '07', '08')

In [48]:
re.sub(r"(\d{4})-(\d+)\-(\d+)", r"\1", "2018-07-08")

'2018'

In [49]:
# ids of items
citation_keys_pairs = {}
for key in citations.keys():
    if collection_items_dict[key.rpartition("/")[2]]["data"]["itemType"] != "attachment":
        try:
            item_dict = collection_items_dict[key.rpartition("/")[2]]
            item_key = item_dict["meta"]["creatorSummary"] + " " + item_dict["meta"]["parsedDate"]
        except: 
            try:
                item_key = item_dict["data"]["title"]
            except:
                item_key = ""
        item_key = re.sub(r"(\d{4})-(\d+)\-(\d+)", r"\1", item_key)
        citation_keys_pairs[item_key] = key

In [50]:
citation_keys_pairs

{'Ballsun-Stanton 2020': '1913534/5MY4KSUI',
 'Wilson 2012': '1913534/SYSTIFZQ',
 'Hanson et al. 2017': '1913534/C2MUHDNG',
 'Morris 2013': '1913534/9YX6ZS7N',
 'Morris 2010': '1913534/627JE7WX',
 'Mullins et al. 2018': '1913534/IFEXKMWT',
 'Harper 2016': '1913534/33TNUAZ3',
 'Kolb 2019': '1913534/95I2Q54Z',
 'Borgman 2015': '1913534/GSAVHWAN',
 'Cayless et al. 2010': '1913534/KRXAF9YL',
 'Laurence 1999': '1913534/AW6LP4AP',
 'Bodard 2008': '1913534/66WIWW57',
 'Liuzzo 2018': '1913534/4WT5APEZ',
 'de Ligt and Tacoma 2016': '1913534/6ZEVHLM6',
 'Wilson and Flohr 2016': '1913534/B99689HI',
 'Verhagen 2019': '1913534/A2U4FIKT',
 'Hanel 2020': '1913534/CLBZUHJ7',
 'Bodard et al. 2021': '1913534/AHA9EWZL',
 'Avanzini et al. 2018': '1913534/LFKD595C',
 'De Santis and Rossi 2018': '1913534/37N8YE3I',
 'Littman and Littman 1973': '1913534/UZDY7HD7',
 'Rabinowitz et al. 2018': '1913534/N8MU7LGT',
 'Bodel 2001': '1913534/4YVYEDQD',
 'Crema and Kobayashi 2020': '1913534/DF62R52E',
 'Kaše 2021': '

# Small test

this way, we can easily generate the data in the form produced by cite2c, combining **collection ID** and **item ID**. 

However, it seems that cite2c does not support group collection. We need to work with our personal collection instead.

Here we test how the citations work. We will use Wilson 2012 as an example. Let put it here <cite data-cite="1913534/SYSTIFZQ"></cite>. Another citation would be here <cite data-cite="1913534/627JE7WX"></cite> or here <cite data-cite="1913534/IFEXKMWT"></cite> (here should be Mullins et al. 2018 - but does not render automatically). <cite data-cite="1913534/MUKI9YSZ"></cite>

insert citation here <cite data-cite="undefined"></cite>.

<cite data-cite="1913534/U48VTMSM"></cite>

<div class="cite2c-biblio"></div>

# Read ipynb as text file

<cite data-cite="1913534/U48VTMSM"></cite>

In [95]:
notebook_text = open("Digital_epigraphy.ipynb").read()
notebook_text[:1000]

'{\n "cells": [\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "title"\n    ]\n   },\n   "source": [\n    "# Inscriptions as data: digital epigraphy in macro-historical perspective "\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "contributor"\n    ]\n   },\n   "source": [\n    "### Petra Hermankova\\n",\n    "Author. Aarhus University, [ORCID: 0000-0002-6349-0540](https://orcid.org/0000-0002-6349-0540)"\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "contributor"\n    ]\n   },\n   "source": [\n    "### Vojtech Kase\\n",\n    "Author. Aarhus University, [ORCID: 0000-0002-6601-1605](http://orcid.org/0000-0002-6601-1605)"\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "contributor"\n    ]\n   },\n   "source": [\n    "### Adela Sobotkova\\n",\n    "Author. Aarhus University, [ORCID:0000-0002-4541-3963](https://orcid.org/0000-0002-4541-3963)"\n   ]\n  

In [96]:
for key in citation_keys_pairs.keys():
    if key in notebook_text:
        print(key, citation_keys_pairs[key])

Wilson 2012 1913534/SYSTIFZQ
Hanson et al. 2017 1913534/C2MUHDNG
Mullins et al. 2018 1913534/IFEXKMWT
Harper 2016 1913534/33TNUAZ3
Kolb 2019 1913534/95I2Q54Z
Borgman 2015 1913534/GSAVHWAN
Cayless et al. 2010 1913534/KRXAF9YL
Laurence 1999 1913534/AW6LP4AP
Bodard 2008 1913534/66WIWW57
Liuzzo 2018 1913534/4WT5APEZ
Wilson and Flohr 2016 1913534/B99689HI
Verhagen 2019 1913534/A2U4FIKT
Hanel 2020 1913534/CLBZUHJ7
Bodard et al. 2021 1913534/AHA9EWZL
Avanzini et al. 2018 1913534/LFKD595C
De Santis and Rossi 2018 1913534/37N8YE3I
Rabinowitz et al. 2018 1913534/N8MU7LGT
Bodel 2001 1913534/4YVYEDQD
Crema and Kobayashi 2020 1913534/DF62R52E
Kaše 2021 1913534/MT2ZRZBH
Kemkes 2020 1913534/AIJX7C5S
Verhagen et al. 2016 1913534/XJBYYW4X
Bowman and Wilson 2009 1913534/6YVHFFUJ
Turchin and Scheidel 2009 1913534/U48VTMSM
Hedrick 1999 1913534/2LT8WIGC
Nawotka 2021 1913534/NEGLBLPH
Lotz 2020 1913534/XUF75FS9
MacMullen 1982 1913534/BGNB6HUT
Trout 2009 1913534/F3Y2FVVY
Feraudi-Gruénais and Grieshaber 2016 1

Working at the level of the province with a couple thousand inscriptions at a time, scholars have started constructing regional diachronic overviews of epigraphic production. Comparative studies between North Africa, Gaul or Greece revealed that epigraphic production in these provinces follows the same diachronic pattern. Inscription numbers peak at the end of the second century AD, during the reign of Septimius Severus (AD 193 - AD 211), and decline abruptly in the beginning of the third century AD (MacMullen 1982; Meyer 1991; Woolf 1996). Researchers started exploring different drivers for such convergence, interrogating the role of funerary habits to the popularity of public status display to the democratisation of citizenship. For instance, Elizabeth Meyer used the example of epitaphs to explain the drop in the number of inscriptions after the Constitutio Antoniniana in AD 212 granted Roman citizenship to all inhabitants of the Roman Empire. According to Meyer, being a Roman citizen lost some of its prestige and so did funerary inscriptions as public markers of societal status (Meyer 1990, 78-81). Such explanations failed to address the phenomenon of epigraphic production in all its breadth and complexity, focusing only on funerary inscriptions from selected regions. Since the time of MacMullen many scholars have attempted to study epigraphic production at the scale of the Empire (e.g., Hedrick 1999; Trout 2009; Beltran Lloris 2014; Bolle, Machado, and Witschel 2017; Nawotka 2021; Blanco Perez 2021). These efforts have been hindered first by the constraints on interoperability and integration of digital datasets, second, by the volume and diversity of epigraphic data, and finally, by the inability to precisely quantify the number of inscriptions at any point in time (Beltran Lloris 2014, 139).

In [97]:
test_paragraph = "Working at the level of the province with a couple thousand inscriptions at a time, scholars have started constructing regional diachronic overviews of epigraphic production. Comparative studies between North Africa, Gaul or Greece revealed that epigraphic production in these provinces follows the same diachronic pattern. Inscription numbers peak at the end of the second century AD, during the reign of Septimius Severus (AD 193 - AD 211), and decline abruptly in the beginning of the third century AD (MacMullen 1982; Meyer 1991; Woolf 1996). Researchers started exploring different drivers for such convergence, interrogating the role of funerary habits to the popularity of public status display to the democratisation of citizenship. For instance, Elizabeth Meyer used the example of epitaphs to explain the drop in the number of inscriptions after the Constitutio Antoniniana in AD 212 granted Roman citizenship to all inhabitants of the Roman Empire. According to Meyer, being a Roman citizen lost some of its prestige and so did funerary inscriptions as public markers of societal status (Meyer 1990, 78-81). Such explanations failed to address the phenomenon of epigraphic production in all its breadth and complexity, focusing only on funerary inscriptions from selected regions. Since the time of MacMullen many scholars have attempted to study epigraphic production at the scale of the Empire (e.g., Hedrick 1999; Trout 2009; Beltran Lloris 2014; Bolle, Machado, and Witschel 2017; Nawotka 2021; Blanco Perez 2021). These efforts have been hindered first by the constraints on interoperability and integration of digital datasets, second, by the volume and diversity of epigraphic data, and finally, by the inability to precisely quantify the number of inscriptions at any point in time (Beltran Lloris 2014, 139)."
print(test_paragraph)

Working at the level of the province with a couple thousand inscriptions at a time, scholars have started constructing regional diachronic overviews of epigraphic production. Comparative studies between North Africa, Gaul or Greece revealed that epigraphic production in these provinces follows the same diachronic pattern. Inscription numbers peak at the end of the second century AD, during the reign of Septimius Severus (AD 193 - AD 211), and decline abruptly in the beginning of the third century AD (MacMullen 1982; Meyer 1991; Woolf 1996). Researchers started exploring different drivers for such convergence, interrogating the role of funerary habits to the popularity of public status display to the democratisation of citizenship. For instance, Elizabeth Meyer used the example of epitaphs to explain the drop in the number of inscriptions after the Constitutio Antoniniana in AD 212 granted Roman citizenship to all inhabitants of the Roman Empire. According to Meyer, being a Roman citize

In [98]:
citations

{'1913534/4DU2BY28': {'type': 'article',
  'title': 'Full Text',
  'URL': 'https://royalsocietypublishing.org/doi/pdf/10.1098/rsif.2017.0367',
  'accessed': {'date-parts': [[2021, 5, 18]]}},
 '1913534/FTDUBX6P': {'type': 'article',
  'title': 'Accepted Version',
  'URL': 'https://ore.exeter.ac.uk/repository/bitstream/10871/36086/2/deleted_FINAL_submission.pdf',
  'accessed': {'date-parts': [[2021, 5, 17]]}},
 '1913534/L47JEQBH': {'type': 'article',
  'title': 'Full Text',
  'URL': 'https://www.degruyter.com/document/doi/10.1515/9783110607208-018/pdf',
  'accessed': {'date-parts': [[2021, 5, 17]]}},
 '1913534/7JEU5M89': {'type': 'article',
  'title': 'Full Text',
  'URL': 'https://www.degruyter.com/document/doi/10.1515/9783110607208-017/pdf',
  'accessed': {'date-parts': [[2021, 5, 14]]}},
 '1913534/AGSJ79AY': {'type': 'article',
  'title': 'Wilson_2012_City Sizes and Urbanization in the Roman Empire.pdf'},
 '1913534/3LU29L3J': {'type': 'article',
  'title': 'Full Text',
  'URL': 'https

In [99]:
test_paragraph = "Working at the level of the province with a couple thousand inscriptions at a time, scholars have started constructing regional diachronic overviews of epigraphic production. Comparative studies between North Africa, Gaul or Greece revealed that epigraphic production in these provinces follows the same diachronic pattern. Inscription numbers peak at the end of the second century AD, during the reign of Septimius Severus (AD 193 - AD 211), and decline abruptly in the beginning of the third century AD (MacMullen 1982; Meyer 1991; Woolf 1996). Researchers started exploring different drivers for such convergence, interrogating the role of funerary habits to the popularity of public status display to the democratisation of citizenship. For instance, Elizabeth Meyer used the example of epitaphs to explain the drop in the number of inscriptions after the Constitutio Antoniniana in AD 212 granted Roman citizenship to all inhabitants of the Roman Empire. According to Meyer, being a Roman citizen lost some of its prestige and so did funerary inscriptions as public markers of societal status (Meyer 1990, 78-81). Such explanations failed to address the phenomenon of epigraphic production in all its breadth and complexity, focusing only on funerary inscriptions from selected regions. Since the time of MacMullen many scholars have attempted to study epigraphic production at the scale of the Empire (e.g., Hedrick 1999; Trout 2009; Beltran Lloris 2014; Bolle, Machado, and Witschel 2017; Nawotka 2021; Blanco Perez 2021). These efforts have been hindered first by the constraints on interoperability and integration of digital datasets, second, by the volume and diversity of epigraphic data, and finally, by the inability to precisely quantify the number of inscriptions at any point in time (Beltran Lloris 2014, 139)."
citations_used = {}
for key in citation_keys_pairs.keys():
    if key in test_paragraph:
        print(key)
        citations_used[citation_keys_pairs[key]] = citations[citation_keys_pairs[key]]
        test_paragraph = test_paragraph.replace(key, '<cite data-cite="' + citation_keys_pairs[key] + '"></cite>')

Hedrick 1999
Nawotka 2021
MacMullen 1982
Trout 2009
Woolf 1996
Meyer 1990


In [100]:
citations_used

{'1913534/2LT8WIGC': {'type': 'article-journal',
  'title': 'Democracy and the Athenian Epigraphical Habit',
  'container-title': 'Hesperia',
  'page': '387-439',
  'volume': '68',
  'issue': '3',
  'URL': 'http://links.jstor.org/sici?sici=0018-098X%28199907%2F09%2968%3A3%3C387%3ADATAEH%3E2.0.CO%3B2-J&origin=crossref',
  'DOI': '10.2307/148494',
  'journalAbbreviation': 'Hesperia',
  'language': 'en',
  'author': [{'family': 'Hedrick', 'given': 'Charles W. Jr.'}],
  'issued': {'date-parts': [[1999]]},
  'accessed': {'date-parts': [[2019, 11, 21]]}},
 '1913534/NEGLBLPH': {'type': 'book',
  'title': 'Epigraphic Culture in the Eastern Mediterranean in Antiquity',
  'publisher': 'Routledge',
  'edition': '1',
  'URL': 'https://www.taylorfrancis.com/books/9781000164800',
  'ISBN': '978-1-00-302530-6',
  'note': 'DOI: 10.4324/9781003025306',
  'language': 'en',
  'editor': [{'family': 'Nawotka', 'given': 'Krzysztof'}],
  'issued': {'date-parts': [[2021]]},
  'accessed': {'date-parts': [[2021

In [101]:
test_paragraph

'Working at the level of the province with a couple thousand inscriptions at a time, scholars have started constructing regional diachronic overviews of epigraphic production. Comparative studies between North Africa, Gaul or Greece revealed that epigraphic production in these provinces follows the same diachronic pattern. Inscription numbers peak at the end of the second century AD, during the reign of Septimius Severus (AD 193 - AD 211), and decline abruptly in the beginning of the third century AD (<cite data-cite="1913534/BGNB6HUT"></cite>; Meyer 1991; <cite data-cite="1913534/HBPZKHXT"></cite>). Researchers started exploring different drivers for such convergence, interrogating the role of funerary habits to the popularity of public status display to the democratisation of citizenship. For instance, Elizabeth Meyer used the example of epitaphs to explain the drop in the number of inscriptions after the Constitutio Antoniniana in AD 212 granted Roman citizenship to all inhabitants 

Working at the level of the province with a couple thousand inscriptions at a time, scholars have started constructing regional diachronic overviews of epigraphic production. Comparative studies between North Africa, Gaul or Greece revealed that epigraphic production in these provinces follows the same diachronic pattern. Inscription numbers peak at the end of the second century AD, during the reign of Septimius Severus (AD 193 - AD 211), and decline abruptly in the beginning of the third century AD (<cite data-cite="1913534/BGNB6HUT"></cite>; Meyer 1991; <cite data-cite="1913534/HBPZKHXT"></cite>). Researchers started exploring different drivers for such convergence, interrogating the role of funerary habits to the popularity of public status display to the democratisation of citizenship. For instance, Elizabeth Meyer used the example of epitaphs to explain the drop in the number of inscriptions after the Constitutio Antoniniana in AD 212 granted Roman citizenship to all inhabitants of the Roman Empire. According to Meyer, being a Roman citizen lost some of its prestige and so did funerary inscriptions as public markers of societal status (<cite data-cite="1913534/MUKI9YSZ"></cite>, 78-81). Such explanations failed to address the phenomenon of epigraphic production in all its breadth and complexity, focusing only on funerary inscriptions from selected regions. Since the time of MacMullen many scholars have attempted to study epigraphic production at the scale of the Empire (e.g., <cite data-cite="1913534/2LT8WIGC"></cite>; <cite data-cite="1913534/F3Y2FVVY"></cite>; Beltran Lloris 2014; Bolle, Machado, and Witschel 2017; <cite data-cite="1913534/NEGLBLPH"></cite>; Blanco Perez 2021). These efforts have been hindered first by the constraints on interoperability and integration of digital datasets, second, by the volume and diversity of epigraphic data, and finally, by the inability to precisely quantify the number of inscriptions at any point in time (Beltran Lloris 2014, 139).



In [102]:
import json

In [103]:
notebook_dict = json.loads(notebook_text)
notebook_dict["metadata"]["cite2c"]["citations"]

{'7109337/2ASLDCJP': {'DOI': '10.1177/0003122418772567',
  'URL': 'http://journals.sagepub.com/doi/10.1177/0003122418772567',
  'abstract': 'Proponents of the Axial Age contend that parallel cultural developments between 800 and 200 BCE in what is today China, Greece, India, Iran, and Israel-Palestine constitute the global historical turning point toward modernity. The Axial Age concept is well-known and influential, but deficiencies in the historical evidence and sociological analysis available have thwarted efforts to evaluate the concept’s major global contentions. As a result, the Axial Age concept remains controversial. Seshat: Global History Databank provides new tools for examining this topic in social formations across Afro-Eurasia during the first two millennia BCE and first millennium CE, allowing scholars to empirically evaluate the varied and contrasting claims researchers have put forward. Results undercut the notion of a specific “age” of axiality limited to a specific ge

In [104]:
notebook_dict["cells"][10:20]

[{'cell_type': 'code',
  'execution_count': 54,
  'metadata': {'tags': ['configuration', 'Python']},
  'outputs': [],
  'source': ['%%capture\n',
   '# install Python libraries\n',
   '!pip install sddk tempun scipy seaborn nltk rpy2 cite2c geopandas cite2c\n',
   '# alternatively:\n',
   '#!pip install -r requirements.txt (eventually we can load reqs via requirements)']},
 {'cell_type': 'code',
  'execution_count': 55,
  'metadata': {'tags': ['configuration', 'Python']},
  'outputs': [],
  'source': ['import geopandas as gpd\n',
   'import cite2c\n',
   'import requests\n',
   'import seaborn as sns\n',
   'import matplotlib.colors as mcolors\n',
   'import matplotlib.pyplot as plt\n',
   'from scipy.stats import trapz\n',
   'import scipy\n',
   'import nltk\n',
   'import json\n',
   'import tempun\n',
   'import sddk\n',
   'import numpy as np\n',
   'import pandas as pd\n',
   'pd.options.display.max_columns = 1000  # to see all columns']},
 {'cell_type': 'code',
  'execution_coun

In [112]:
notebook_text = open("Digital_epigraphy.ipynb").read()
notebook_text[:1000]

'{\n "cells": [\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "title"\n    ]\n   },\n   "source": [\n    "# Inscriptions as data: digital epigraphy in macro-historical perspective "\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "contributor"\n    ]\n   },\n   "source": [\n    "### Petra Hermankova\\n",\n    "Author. Aarhus University, [ORCID: 0000-0002-6349-0540](https://orcid.org/0000-0002-6349-0540)"\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "contributor"\n    ]\n   },\n   "source": [\n    "### Vojtech Kase\\n",\n    "Author. Aarhus University, [ORCID: 0000-0002-6601-1605](http://orcid.org/0000-0002-6601-1605)"\n   ]\n  },\n  {\n   "cell_type": "markdown",\n   "metadata": {\n    "tags": [\n     "contributor"\n    ]\n   },\n   "source": [\n    "### Adela Sobotkova\\n",\n    "Author. Aarhus University, [ORCID:0000-0002-4541-3963](https://orcid.org/0000-0002-4541-3963)"\n   ]\n  

In [113]:
citations_used = {}
for key in citation_keys_pairs.keys():
    if key in notebook_text:
        citations_used[citation_keys_pairs[key]] = citations[citation_keys_pairs[key]]
        notebook_text = notebook_text.replace(key, "<cite data-cite=\'" + citation_keys_pairs[key] + "\'></cite>")

In [116]:
notebook_dict = json.loads(notebook_text)
notebook_dict["metadata"]["cite2c"]["citations"] = citations_used

In [118]:
with open("Digital_epigraphy_cite2c_test1.ipynb", "w") as f:
    json.dump(notebook_dict, f)